[package]
name = "nrf52840-embassy"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
embassy-executor = {  git = "https://github.com/pbert519/embassy" , branch = "nrf-pdm-support" }
embassy-sync = {  git = "https://github.com/pbert519/embassy" , branch = "nrf-pdm-support" }
embassy-nrf = { git = "https://github.com/pbert519/embassy" , branch = "nrf-pdm-support" }
embassy-time = { git = "https://github.com/pbert519/embassy" , branch = "nrf-pdm-support" }
embassy-embedded-hal = {  git = "https://github.com/pbert519/embassy" , branch = "nrf-pdm-support" }


[dependencies]
embassy-executor = { version = "0.1.0", features = ["defmt", "nightly", "integrated-timers"] }
embassy-sync = { version = "0.1.0", features = ["defmt"] }
embassy-nrf = { version = "0.1.0", features = ["defmt", "nrf52840", "time-driver-rtc1", "gpiote", "unstable-traits", "nightly"] }
embassy-time = { version = "0.1.0", features = ["defmt"] }
embassy-embedded-hal = "0.1.0" 
embedded-hal-async = "0.1.0-alpha.1"

static_cell = "1.0"
defmt = "0.3"
defmt-rtt = "0.3"
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
panic-probe = { version = "0.3", features = ["print-defmt"] }

microfft = "0.5.0"
ssd1306 = "0.7.1"
embedded-graphics = "0.7.1"