[package]
name = "nrf52840-embassy"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy" }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy" }

[dependencies]
embassy = { version = "0.1.0", features = ["defmt", "nightly"] }
embassy-nrf = { version = "0.1.0", features = ["defmt", "nrf52840", "time-driver-rtc1", "gpiote"] }

defmt = "0.3"
defmt-rtt = "0.3"
cortex-m = { version = "0.7.3"}
cortex-m-rt = "0.7.0"
panic-probe = { version = "0.3", features = ["print-defmt"] }